Test feature: fetch-tags - complete

diff --git a/git-artifact b/git-artifact
--- a/git-artifact
+++ b/git-artifact
@@ -234,12 +234,18 @@ cmd_reset() {
 }
 
 cmd_fetch-co() {
+    local _current_branch
+    _current_branch=$(git branch --show-current)
     if [ -n "${arg_artifacttag:-}" ]; then 
         echo "INFO: fetching tag: ${arg_artifacttag}"
         git fetch origin +refs/tags/"${arg_artifacttag}":refs/tags/"${arg_artifacttag}"
         echo "INFO: checkout the tag: ${arg_artifacttag} in detached HEAD"
-        git checkout -f refs/tags/"${arg_artifacttag}"
-        [ -n "${arg_branch:-}" ] && echo "WARN: skipping the branch as tag is prio"
+        if [ -n "${arg_branch:-}" ] ; then 
+            echo "INFO: You provided a branch - checkout $arg_branch and set it to refs/tags/${arg_artifacttag}"
+            git checkout -B "${arg_branch}" refs/tags/"${arg_artifacttag}"
+        else
+            git checkout -f refs/tags/"${arg_artifacttag}"
+        fi 
     elif [ -n "${arg_branch:-}" ]; then 
         echo "INFO: fetching branch: ${arg_branch}"
         git fetch origin +refs/heads/"${arg_branch}":refs/heads/"${arg_branch}"
@@ -257,10 +263,16 @@ cmd_fetch-co-latest() {
 
 
 cmd_fetch-tags() {
-    echo "EXPERIMENTAL: untested command fetch-tags"
-    for tag in $( git ls-remote --tags origin | grep -v '\^{}' | grep -E "[a-f0-9].*refs/tags/${arg_sha1}" | cut  -f2 ); do 
-        git fetch orgin "+$tag:$tag"
-    done 
+    echo "Getting tags from: $arg_sha1"
+    tags=$(git ls-remote --tags origin | grep '\^{}' | grep -E "^${arg_sha1}" | cut  -f2 | cut -d ^ -f 1) || tags=""
+    if [ -n "${tags:-}" ]; then 
+        for tag in $tags ; do 
+            git fetch origin "+$tag:$tag"
+        done 
+    else
+        echo "ERROR: No tags found"
+        exit 1
+    fi
 }
 
 main () {
