Add pipeline to test against git latest, 2.36.2, 2.26.2

diff --git a/git-artifact b/git-artifact
--- a/git-artifact
+++ b/git-artifact
@@ -284,7 +284,14 @@ cmd_fetch-co() {
 find-latest() {
     local -n _latest_tag=${1}
     # https://stackoverflow.com/questions/10649814/get-last-git-tag-from-a-remote-repo-without-cloning
-    _latest_tag=$(git ls-remote --tags --refs --sort='-version:refname' origin ${arg_regex} | head --lines=1 | cut  -f2 | cut -d / -f3-)
+    _latest_tag=$(git ls-remote --tags --refs --sort='-version:refname' origin ${arg_regex} | head -n 1 | cut  -f2 | cut -d / -f3-) || {
+        local exit_code=$?
+        if [[ $exit_code -ne 141 ]]; then 
+            #https://unix.stackexchange.com/questions/580117/debugging-sporadic-141-shell-script-errors
+            echo "ERROR: Something unknown happend.."
+            exit 1
+        fi
+    } 
     if [ -z "${_latest_tag:-}" ]; then 
         echo "ERROR: No tag found using regex: ${arg_regex} "
         exit 1
