gh-17 adding list and summary and prune function (breaking: rename option regex to glob) (#32)
Breaking:
- option regex replaced with glob as was implemented as glob. regex might come later using grep as filter. It is still defaulting to * if not given

New features:
- added: function "list" artifacts command with glob pattern
- added: function "summary" using delimiter (default: /) . it finds all first fields and then counts number of artifacts given the pattern
- added: function "prune". given a pattern find all artifacts and then keep the last amount given (default: 20).  It is supporting --dryrun option

Tests:
- refactor tests to functions and enable single test case execution
- tests for new functions

diff --git a/git-artifact b/git-artifact
--- a/git-artifact
+++ b/git-artifact
@@ -76,14 +76,20 @@ push            push a tag
 add-n-push      add and commit files to repo and then push them
 fetch-co   	    fetch tag from remote and checkout it out
 reset           reset workspace and branches
+list            list all tags in the repo given a glob pattern
+summary         print a summary of the tags in the repo
+prune           prune tags in the repo given a glob pattern and keep amount of tags
 find-latest     Find the latest tags from reqex and print it
 fetch-co-latest Get latest tag form remote using grep reg-ex and reset hard to it
 fetch-tags      Fetch all tags that points to a sha1 or HEAD - Useful in relation to detached HEAD and submodules
-
 --
-h,help          show the help
+h               show the help
 q               quiet
+v,verbose       verbose
 d               show debug messages
+
+ option for 'prune'
+dryrun          dry run - do not execute any commands ( optional for prune)
 
  options for 'init' and 'clone'
 u,url=        the remote url
@@ -95,11 +101,17 @@ b,branch=     use branch for local changes and pushes
  options for 'add-n-tag', 'push', 'add-n-push', 'fetch-co'
 t,tag=         the tag to be created
 
- options for 'fetch-co-latest', 'find-latest'
-r,regex=       the reg-ex pattern to latest of
+ options for 'fetch-co-latest', 'find-latest', 'list', 'prune'
+g,glob=       the glob pattern search remote for tags
 
  options for 'fetch-tags'
 s,sha1=       The sha1 of which to get tags from from 
+
+ options for 'prune'
+k,keep=       The amount of tags to keep - default is 20 
+
+ options for 'summary'
+delimiter=    The delimiter to use for the summary - default is '/'
 "
 }
 
@@ -329,10 +341,74 @@ cmd_fetch-co() {
     git log -1 --oneline --decorate
 }
 
+cmd_prune() {
+    
+    mapfile -t tag_array < <(git ls-remote --tags --ref --sort=v:refname origin "refs/tags/${arg_glob:-*}" | cut -d / -f 3-)
+
+    if [[ ${#tag_array[@]} -eq 0 ]]; then
+        echo "No tags found matching glob: ${arg_glob}"
+        exit 0
+    fi
+
+    tags_to_be_pruned=""
+    tags_amount_to_prune=$(( ${#tag_array[@]} - arg_keep ))
+    for ((i = 0; i < ${#tag_array[@]}; i++)); do
+        tag="${tag_array[$i]}"
+        if [[ $i -lt $tags_amount_to_prune ]]; then
+            [[ ${arg_verbose:-} ]] && echo "Would prune tag: $tag"
+            # Uncomment the next line to actually delete the tag
+            tags_to_be_pruned+="$tag "
+        else
+            true
+            #echo "Keeping tag: $tag"
+        fi
+    done
+    printf "Amount of tags total: %s\n" "${#tag_array[@]}" 
+    printf "Amount of tags to be pruned: %s\n" "${tags_amount_to_prune}" 
+    printf "Amount of tags to be kept: %s\n" "${arg_keep}" 
+    if [[ ${arg_dryrun:-} == 1 ]] ; then
+        echo "Dry run - not executing prune command"
+    else
+        echo "$tags_to_be_pruned" | xargs --no-run-if-empty git push origin --delete
+    fi
+}
+
+cmd_list() {
+    if [[ ${arg_quiet:-} -ne 1 ]]; then
+        git ls-remote --tags --ref --sort=v:refname origin  "refs/tags/${arg_glob:-*}" | cut -d / -f 3-
+    fi
+    printf "Tags found: %s : %s\n" "${arg_glob}" "$(git ls-remote --tags --ref --sort=v:refname origin  "refs/tags/${arg_glob:-*}" | wc -l)"
+}
+
+cmd_summary() {
+    declare -A tags
+    read_remote_tags_to_map tags
+    echo "Summary of of amount of tags in using delimiter: ${arg_delimiter} and filter on first column"
+    echo "----------------------------------------------------------------------------------------"
+ 
+    # print the hash map with a count of tags of each key
+    for k in "${!tags[@]}"; do
+        amount=$(echo -n "${tags[$k]}" | wc -l)
+        echo "$k : ${amount}"
+    done
+}
+
+read_remote_tags_to_map() {
+    local -n _tags=${1}
+
+    while read -r line; do
+        # Extract the tag name from the line
+        key="${line#*refs/tags/}"
+        key="${key%%"$arg_delimiter"*}"
+        info="${line#*"$arg_delimiter"}"
+        _tags["$key"]+="$info"$'\n'
+    done < <(git ls-remote --tags --ref --sort=v:refname origin refs/tags/*)
+}
+
 find-latest() {
     local -n _latest_tag=${1}
     # https://stackoverflow.com/questions/10649814/get-last-git-tag-from-a-remote-repo-without-cloning
-    _latest_tag=$(git ls-remote --tags --refs --sort='-version:refname' origin "refs/tags/${arg_regex}" | head -n 1 | cut  -f2 | cut -d / -f3-) || {
+    _latest_tag=$(git ls-remote --tags --refs --sort='-version:refname' origin  "refs/tags/${arg_glob}" | head -n 1 | cut  -f2 | cut -d / -f3-) || {
         local exit_code=$?
         if [[ $exit_code -ne 141 ]]; then 
             #https://unix.stackexchange.com/questions/580117/debugging-sporadic-141-shell-script-errors
@@ -341,7 +417,7 @@ find-latest() {
         fi
     } 
     if [ -z "${_latest_tag:-}" ]; then 
-        echo "ERROR: No tag found using regex: ${arg_regex} "
+        echo "ERROR: No tag found using glob pattern: ${arg_glob} "
         exit 1
     fi
 }
@@ -376,7 +452,7 @@ cmd_fetch-tags() {
 
 main () {
     [[ ${debug:-} == true ]] && {
-        echo "debug: ${debug}"
+        debug "debug: ${debug}"
         set -x
     }
     if [[ $# -eq 0 ]] ; then
@@ -390,6 +466,7 @@ main () {
     arg_artifacttag=
     arg_branch=
     arg_path=
+    arg_delimiter="/"
     while test $# -gt 1
     do
         opt="$1" # command
@@ -397,10 +474,16 @@ main () {
 
         case "$opt" in
         -q)
-            GIT_QUIET=1
+            arg_quiet=1
             ;;
         -d)
             arg_debug=1
+            ;;
+        --dryrun|-dr)
+            arg_dryrun=1
+            ;;
+        --verbose|-v)
+            arg_verbose=1
             ;;
         --url|-u)
             arg_remoteurl="$1"
@@ -418,12 +501,24 @@ main () {
             arg_path="$1"
             shift
             ;;
-        --regex|-r)
-            arg_regex="$1"
+        --glob|-g)
+            arg_glob="$1"
             shift
             ;;
         --sha1|-s)
             arg_sha1="$1"
+            shift
+            ;;
+        --keep|-k)
+            arg_keep="$1"
+            if ! [[ "$arg_keep" =~ ^[0-9]+$ ]]; then
+                echo "INFO: --keep is not a number"
+                exit 1
+            fi
+            shift
+            ;;
+        --delimiter)
+            arg_delimiter="$1"
             shift
             ;;
         --)
@@ -493,13 +588,27 @@ main () {
                 . git-sh-setup
                 require_work_tree
                 ;;
-        fetch-co-latest|find-latest)
+        fetch-co-latest|find-latest|list)
                 # shellcheck source=/dev/null
                 . git-sh-setup
                 require_work_tree
-                if test -z "${arg_regex:-}" ; then
-                    echo "INFO: -r|--regex is not set: Defaulting to '*' (all tags)."
-                    arg_regex="*"
+                if test -z "${arg_glob:-}" ; then
+                    echo "INFO: -g|--glob is not set: Defaulting to '*' (all tags)."
+                    arg_glob="*"
+                fi
+                ;;
+        summary)
+                # shellcheck source=/dev/null
+                . git-sh-setup
+                require_work_tree
+                ;;
+        prune)
+                # shellcheck source=/dev/null
+                . git-sh-setup
+                require_work_tree
+                if [[ -z "$arg_keep" ]]; then
+                    echo "INFO: --keep is not set: Defaulting to 20"
+                    arg_keep=20
                 fi
                 ;;
         fetch-tags)
@@ -517,7 +626,7 @@ main () {
                 ;;
     esac
     debug "command: {$arg_command}"
-    debug "quiet: {$GIT_QUIET}"
+    debug "quiet: {${arg_quiet:-0}}"
     debug "opts: {$*}"
     debug
 
