EXP: add find-latest with regex command - fix

diff --git a/git-artifact b/git-artifact
--- a/git-artifact
+++ b/git-artifact
@@ -139,9 +139,8 @@ cmd_init() {
     local _base_branch=
     set_base_branch _base_branch
 
-    git init  "$_dir" 
+    git init -b ${_base_branch} "$_dir" 
     cd "$_dir"
-    git checkout -B "${_base_branch}" 
     git_local_config
     git remote add origin "$arg_remoteurl"
     git config --local remote.origin.fetch "+refs/heads/${_base_branch}:refs/remotes/origin/${_base_branch}"
@@ -190,7 +189,7 @@ cmd_clone() {
 
     if [[ -n ${arg_branch:-} ]]; then
         echo "INFO: Init branch: ${arg_branch}"
-        git checkout -b "${arg_branch}"
+        git checkout -B "${arg_branch}"
         git branch "${arg_branch}" --set-upstream-to "origin/${_remote_default_branch}"
     fi
 
@@ -282,15 +281,28 @@ cmd_fetch-co() {
     git log -1 --oneline --decorate
 }
 
-cmd_find-latest() {
-    git ls-remote --tags origin | grep -v '\^{}' | grep -E "[a-f0-9].*refs/tags/${arg_regex}" | tail -1 | cut  -f2 | cut -d / -f 3-
+find-latest() {
+    local -n _latest_tag=${1}
+    # https://stackoverflow.com/questions/10649814/get-last-git-tag-from-a-remote-repo-without-cloning
+    _latest_tag=$(git ls-remote --tags --refs --sort='-version:refname' origin ${arg_regex} | head --lines=1 | cut  -f2 | cut -d / -f3-)
+    if [ -z "${_latest_tag:-}" ]; then 
+        echo "ERROR: No tag found using regex: ${arg_regex} "
+        exit 1
+    fi
 }
 
+cmd_find-latest() {
+    local __latest_tag
+    find-latest __latest_tag
+    printf "%s\n" "$__latest_tag"
+}
+
+
 cmd_fetch-co-latest() {
-    latest_tag=$(cmd_find_latest)
-    echo "Found: $latest_tag" 
+    latest_tag=""
+    find-latest latest_tag
     git fetch origin +$latest_tag:$latest_tag
-    git reset --hard $latest_tag
+    git checkout $latest_tag
 }
 
 
